version: "3.8"

services:
  pocketbase-app:
    container_name: pocketbase-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/pb_data
